config/routes.rb
Myflix::Application.routes.draw do
  root to: 'pages#root'

  get 'ui(/:action)', controller: 'ui'
  get '/home', to: 'videos#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/', to: 'pages#root'
  get '/register', to: 'users#new'
  post '/register', to: 'users#create'
  get '/logout', to: 'sessions#destroy'
  get '/my_queue', to: 'queue_items#index'
  post '/update_queue', to: 'queue_items#update_queue'
  get '/people', to: 'relationships#index'
  resources :forgot_passwords, only:[:new, :create]
  get '/forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :reset_passwords, only:[:show, :create]
  get '/expired_token', to: 'reset_passwords#invalid'

  resources :invitations, only:[:new, :create]

  resources :videos, only: [:show, :index] do
    collection do
      get :search, to: 'videos#search'  
    end

    resources :reviews, only: [:create]
  end

  resources :users, only: [:show, :create, :edit, :update]
  get '/new_with_invitation_token', to: 'users#new_with_invitation_token'


  resources :categories
  resources :relationships, only: [:create, :destroy]
  resources :queue_items, only: [:create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  include Tokenable

  has_many :reviews
  has_secure_password validations: false
  has_many :queue_items, order: :position
  has_many :following_relationships, class_name: "Relationship", foreign_key: :follower_id

  validates :email, uniqueness: true, presence: true
  validates :fullname, presence: true

  def normalize_position
    queue_items.each_with_index do |queue_item, index|
      queue_item.update_attributes(position: index+1)
    end
  end

  def follows?(another_user)
    following_relationships.map(&:leader).include?(another_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user, only: [:show]
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @queue_item = @user.queue_items
    @review = @user.reviews
  end

  def create
    @user = User.new(user_params)

    if @user.save
      AppMailer.welcome_email(@user).deliver
      flash[:success] = "Your account has been created!"
      session[:user_id] = @user.id
      redirect_to home_path
    else
      render :new
    end
  end

  def new_with_invitation_token
    invitation = Invitation.where(token: params[:token]).first
    if invitation
      @user = User.new(email: invitation.recipiant_email)
      render :new
    else
      redirect_to expired_token_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :email, :fullname)
  end
end

app/views/users/new.html.haml
%section.register.container
  .row
    .col-sm-10.col-sm-offset-1
      / = render 'shared/errors', obj: @user
      = bootstrap_form_for(@user, url: register_path) do |f|
        %header
          %h1 Register
        %fieldset
          = f.email_field :email
          = f.text_field :fullname, label: "Full Name"
          = f.password_field :password
          = f.submit("Submit")

app/views/users/show.html.haml
%section.user.container
  .row
    .col-sm-10.col-sm-offset-1
      %article
        %header
          %img(src="http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest('knwang@gmail.com'.downcase)}?s=40")
          %h2 #{@user.fullname}'s video collections (#{@queue_item.count})
          = link_to "Follow", relationships_path(leader_id: @user.id), class: "btn btn-primary", method: :create unless @user.id == current_user.id || current_user.follows?(@user)
        %table.table
          %thead
            %tr
              %th(width="30%") Video Title
              %th(width="15%") Genre
          %tbody
            - @queue_item.each do |queue_item|
              %tr
                %td
                  = link_to queue_item.video.title
                %td
                  = link_to queue_item.video.category.title

%section.user_reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      %header
        %h3 #{@user.fullname}'s Reviews (#{@review.count})
      %ul
        - @review.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %p
                  = link_to review.video.title, review.video
                %col Rating: #{review.rating} / 5
              .col-sm-8
                %p #{review.content}