config/routes.rb
Myflix::Application.routes.draw do
  root to: 'pages#root'

  get 'ui(/:action)', controller: 'ui'
  get '/home', to: 'videos#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/', to: 'pages#root'
  get '/register', to: 'users#new'
  post '/register', to: 'users#create'
  get '/logout', to: 'sessions#destroy'
  get '/my_queue', to: 'queue_items#index'
  post '/update_queue', to: 'queue_items#update_queue'
  get '/people', to: 'relationships#index'
  resources :forgot_passwords, only:[:new, :create]
  get '/forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :reset_passwords, only:[:show, :create]
  get '/expired_token', to: 'reset_passwords#invalid'

  resources :invitations, only:[:new, :create]

  resources :videos, only: [:show, :index] do
    collection do
      get :search, to: 'videos#search'  
    end

    resources :reviews, only: [:create]
  end

  resources :users, only: [:show, :create, :edit, :update]
  get '/new_with_invitation_token', to: 'users#new_with_invitation_token'


  resources :categories
  resources :relationships, only: [:create, :destroy]
  resources :queue_items, only: [:create, :destroy]
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_many :reviews, order: "created_at DESC"
  has_many :queue_items
  belongs_to :category

  validates :title, presence: true
  validates :description, presence: true

  def self.search_by_title(search_term)
    where("title LIKE ?", "%#{search_term}%").order("created_at DESC")
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :require_user, :find_user

  def index
    @videos = Video.all
    @category = Category.all
  end

  def search
    @videos = Video.search_by_title(params[:q])
    if @videos == []
      redirect_to :back
    else
      render :index
    end
  end

  def show
    @video = Video.find_by id: params[:id]
    @review = @video.reviews
  end

  private

  def find_user
    @user = User.find(session[:user_id])
  end
end

app/views/videos/index.html.haml
%article.video_category
  - @category.each do |category|
    %header
      %h3= category.title
      .videos.row
        - category.display_most_recent_videos.each do |video|
          .video.col-sm-2
            = link_to video, nil do
              %img(src="#{video.small_cover_url}")

app/views/videos/show.html.haml
%article.video
  .container
    .row
      .video_large_cover.col-sm-7.col-sm-offset-1
        %img(src="#{@video.large_cover_url}")
      .video_info.col-sm-3
        %header
          %h3= @video.title
          %span Rating: NA
        %p= @video.description
        %a.btn.btn-primary(href="") Watch Now
        = link_to "+ My Queue", queue_items_path(video_id: @video.id), method: :post, class: 'btn'

%section.reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      = form_for [@video, Review.new] do |f|
        %fieldset
          .form-group
            %label Rate this video
            = f.select :rating, options_for_select([5,4,3,2,1].map {|number| [pluralize(number, "Star")]})
          .form-group
            %label Write Review
            = f.text_area :content, rows: 6, class: "span6"
        %fieldset.form-group.actions.clearfix
          %input(type="submit" value="Submit" class="btn")
          = link_to "Cancel", @video
      %header
        %h3 User Reviews (#{@review.count})
      %ul
        - @review.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %span Rating: #{review.rating} / 5
                %p by
                = link_to review.user.fullname, review.user
              .col-sm-8
                %p #{review.content}