config/routes.rb
Myflix::Application.routes.draw do
  root to: 'pages#root'

  get 'ui(/:action)', controller: 'ui'
  get '/home', to: 'videos#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/', to: 'pages#root'
  get '/register', to: 'users#new'
  post '/register', to: 'users#create'
  get '/logout', to: 'sessions#destroy'
  get '/my_queue', to: 'queue_items#index'
  post '/update_queue', to: 'queue_items#update_queue'
  get '/people', to: 'relationships#index'
  resources :forgot_passwords, only:[:new, :create]
  get '/forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :reset_passwords, only:[:show, :create]
  get '/expired_token', to: 'reset_passwords#invalid'

  resources :invitations, only:[:new, :create]

  resources :videos, only: [:show, :index] do
    collection do
      get :search, to: 'videos#search'  
    end

    resources :reviews, only: [:create]
  end

  resources :users, only: [:show, :create, :edit, :update]
  get '/new_with_invitation_token', to: 'users#new_with_invitation_token'


  resources :categories
  resources :relationships, only: [:create, :destroy]
  resources :queue_items, only: [:create, :destroy]
end

app/views/shared/_errors.html.haml
- if obj.errors.any?
  .alert.alert-error
    %h5 Please correct the following errors.
    %ul
      - obj.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_header.html.haml
%section#top-header.row
  %h1.col-md-2
    = link_to "MyFLiX"
  - if logged_in?
    %ul.col-md-4.clearfix
      %li= link_to "Videos"
      %li= link_to "My Queue"
      %li= link_to "People"
    = form_tag(search_videos_path, method: "get", class: 'col-md-5.navbar-form') do 
      = text_field_tag(:q, nil, placeholder: "Search for video titles here.", class: 'form-control')
      = submit_tag("Search", class: 'btton btn btn-default')
    #user_links.pull-right
      %ul
        %li.dropdown
          %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
            = current_user.fullname
            %b.caret
          %ul.dropdown-menu(role="menu" aria-labelledby="dlabel")
            %li
              %a(href="#") Account
              %a(href="#") Plan and Billing
              %a= link_to("Logout", logout_path)

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)