config/routes.rb
Myflix::Application.routes.draw do
  root to: 'pages#root'

  get 'ui(/:action)', controller: 'ui'
  get '/home', to: 'videos#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/', to: 'pages#root'
  get '/register', to: 'users#new'
  post '/register', to: 'users#create'
  get '/logout', to: 'sessions#destroy'
  get '/my_queue', to: 'queue_items#index'
  post '/update_queue', to: 'queue_items#update_queue'
  get '/people', to: 'relationships#index'
  resources :forgot_passwords, only:[:new, :create]
  get '/forgot_password_confirmation', to: 'forgot_passwords#confirm'
  resources :reset_passwords, only:[:show, :create]
  get '/expired_token', to: 'reset_passwords#invalid'

  resources :invitations, only:[:new, :create]

  resources :videos, only: [:show, :index] do
    collection do
      get :search, to: 'videos#search'  
    end

    resources :reviews, only: [:create]
  end

  resources :users, only: [:show, :create, :edit, :update]
  get '/new_with_invitation_token', to: 'users#new_with_invitation_token'


  resources :categories
  resources :relationships, only: [:create, :destroy]
  resources :queue_items, only: [:create, :destroy]
end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController
  def show
  	user = User.where(token: params[:id]).first
  	@user = user
  	if user
  	  @token = user.token
  	else
      redirect_to expired_token_path
    end
  end

  def create
  	user = User.where(token: params[:token]).first
  	if user
  	  user.password = params[:password]
  	  user.generate_token
	    user.save
	    flash[:success] = "Password reset successed! Now please login!"
	    redirect_to login_path
  	else
      redirect_to expired_token_path
  	end
  end

  def invalid
  end
end

app/views/reset_passwords/invalid.html.haml
%section.invalid_token.container
  .row
    .col-sm-10.col-sm-offset-1
      %p Your reset password link is expired.

app/views/reset_passwords/show.html.haml
%section.reset_password.container
  .row
    .col-sm-10.col-sm-offset-1
      = form_tag reset_passwords_path do
        %header
          %h1 Reset Your Password
        %fieldset.form-group
          = label_tag :password, "New Password"
          .row
            .col-sm-4
              = text_field_tag :password
              = hidden_field_tag :token, @token
        %fieldset.form-group.action
          %input(type="submit" value="Reset Password" class="btn btn-default")